### ISSUE TITLE
可以帮忙部署吗

### ISSUE THREAD

**Issue by ranxu45675** [Fxk2020/clawerTaobao#1]
我们的作业也是这个，不知道怎么运行

**Comment by Fxk2020** [comment]
才看到还需要用吗


 ***@***.***
 ***@***.***
  



---- 回复的原邮件 ----
发件人  ***@***.***> 日期  2023年05月23日 15:09 收件人  ***@***.***> 抄送至  ***@***.***> 主题  Re: [Fxk2020/clawerTaobao] 可以帮忙部署吗 (Issue #1)  

Closed #1 as not planned.
